# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTest0():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_test0(self):
    self.driver.get("https://www.google.com/")
    self.driver.set_window_size(697, 706)
    self.driver.find_element(By.NAME, "q").click()
    self.driver.find_element(By.NAME, "q").send_keys(Keys.DOWN)
    self.driver.find_element(By.NAME, "q").send_keys("amazon")
    self.driver.find_element(By.NAME, "q").send_keys(Keys.ENTER)
    element = self.driver.find_element(By.CSS_SELECTOR, ".cfxYMc")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".cfxYMc > span").click()
    self.driver.execute_script("window.scrollTo(0,52)")
    self.driver.find_element(By.CSS_SELECTOR, ".hovering > .feed-right").click()
    self.driver.find_element(By.ID, "add-to-cart-button").click()
    element = self.driver.find_element(By.ID, "attach-close_sideSheet-link")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, "#attach-sidesheet-view-cart-button .a-button-input").click()
  
